---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crssi-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: crssi-nfs-pv
  storageClassName: crssi-sc
  selector:
    matchLabels:
      app: "crssi"